# Generated by Django 5.0.1 on 2024-01-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0007_subscribeduser_delete_subscribedusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='email',
            new_name='u_email',
        ),
        migrations.RemoveField(
            model_name='subscribeduser',
            name='created_date',
        ),
    ]
