# Generated by Django 5.0.1 on 2024-01-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0011_rename_blog_cat_blog_post_blog_cats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='blog_cats',
            new_name='blog_cat',
        ),
    ]
