# Generated by Django 5.0.1 on 2024-02-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0012_rename_blog_cats_blog_post_blog_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='like_btn',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='view_btn',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
